version: '3'

services:
  mariadb-container:
    container_name: mariadb-container
    image: mariadb
    environment:
      MYSQL_ROOT_PASSWORD: 6980
      MYSQL_DATABASE: mydatabase
      MYSQL_USER: movie
      MYSQL_PASSWORD: movie
    ports:
      - "3306:3306"
    networks:
      - movie-network
    volumes:
      - mariadb-data:/var/lib/mysql

  movie-server:
    container_name: movie-server
    build:
      context: .
      dockerfile: Dockerfile
    image: movie-image
    ports:
      - "8080:8080"
    environment:
      DATABASE_URL: jdbc:mariadb://mariadb-container:3306/mydatabase
      DATABASE_USERNAME: movie
      DATABASE_PASSWORD: movie
      image: movie-image
    depends_on:
      - mariadb-container
    networks:
      - movie-network

networks:
  movie-network:

volumes:
  mariadb-data: